name: 'Sync Setup'
description: 'Common setup steps for image sync workflows'
inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.11'
  docker-registry:
    description: 'Docker registry URL'
    required: true
  docker-username:
    description: 'Docker registry username'
    required: true
  docker-password:
    description: 'Docker registry password'
    required: true
  skip-docker:
    description: 'Skip Docker setup'
    required: false
    default: 'false'
  skip-github-cli:
    description: 'Skip GitHub CLI installation'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'
        cache-dependency-path: '.github/scripts/requirements.txt'

    - name: Install Python dependencies
      shell: bash
      run: pip install -r .github/scripts/requirements.txt

    - name: Set up Docker Buildx
      if: inputs.skip-docker != 'true'
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Container Registry
      if: inputs.skip-docker != 'true'
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.docker-registry }}
        username: ${{ inputs.docker-username }}
        password: ${{ inputs.docker-password }}

    - name: Install GitHub CLI
      if: inputs.skip-github-cli != 'true'
      shell: bash
      run: |
        type -p gh >/dev/null || (
          sudo mkdir -p -m 755 /etc/apt/keyrings &&
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null &&
          sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg &&
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null &&
          sudo apt update &&
          sudo apt install gh -y
        )
