name: Sync Guacamole Server

on:
  schedule:
    - cron: '0 18 * * *'  # Daily at 2 AM UTC+8 (18:00 UTC)
  workflow_dispatch:

jobs:
  sync:
    uses: ./.github/workflows/sync-template.yml
    with:
      repo: 'apache/guacamole-server'
      sync_type: 'tag'
      dockerfile: |
        FROM guacamole/guacd:{VERSION}
        USER root
        RUN apk add --no-cache curl \
            && apk add font-wqy-zenhei --no-cache --repository https://nl.alpinelinux.org/alpine/edge/community \
            && curl -OL https://github.com/ryanoasis/nerd-fonts/releases/latest/download/UbuntuMono.tar.xz \
            && apk del curl \
            && mkdir /usr/share/fonts/ubuntu \
            && tar -xf UbuntuMono.tar.xz -C /usr/share/fonts/ubuntu \
            && rm UbuntuMono.tar.xz \
            && fc-cache -f -v
        USER guacd
    secrets: inherit
