name: Sync Prowlarr

on:
  schedule:
    - cron: '0 18 * * *'  # Daily at 2 AM UTC+8 (18:00 UTC)
  workflow_dispatch:

jobs:
  sync:
    uses: ./.github/workflows/sync-template.yml
    with:
      repo: 'linuxserver/docker-prowlarr'
      sync_type: 'release'
      source_images: |
        - lscr.io/linuxserver/prowlarr
    secrets: inherit
